### ISSUE TITLE
make chef-cook server error

### ISSUE THREAD

**Issue by IuliiSe** [opengovfoundation/madison#1063]
Please help.

```
~/madison# make chef-cook server=user@hostname
knife solo cook user@hostname -c .chef/knife.rb
Running Chef on hostname...
Checking Chef version...
user@hostname's password: 

Installing Berkshelf cookbooks to 'config/chef/cookbooks'...
Resolving cookbook dependencies...
Fetching 'base-server' from git@github.com:opengovfoundation/cookbook-base-server.git (at master)

ERROR: Berkshelf::GitCommandError: Git error: command `git clone git@github.com:opengovfoundation/cookbook-base-server.git "/root/.berkshelf/.cache/git/c5687aeade2da2ad96fa1ed768a1d47db0d07a17" --bare --no-hardlinks` failed. If this error persists, try removing the cache directory at '/root/.berkshelf/.cache/git/c5687aeade2da2ad96fa1ed768a1d47db0d07a17'.Output from the command:

Cloning into bare repository '/root/.berkshelf/.cache/git/c5687aeade2da2ad96fa1ed768a1d47db0d07a17'...
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights and the repository exists.
Makefile:107: recipe for target 'chef-cook' failed
make: *** [chef-cook] Error 100```

**Comment by sethetter** [comment]
@IuliiSe I pushed a commit to the `dev` branch to update the git urls in the Berksfile to use https instead of git. Clone that down, do `rm -rf config/chef/cookbooks` then `make berks` and try the `chef-prepare` and `chef-cook` commands again.

**Comment by IuliiSe** [comment]
@sethetter I've completed the suggested step. But, `chef-cook` still return errors:

```
  ================================================================================
  Recipe Compile Error in /root/chef-solo/local-mode-cache/cache/cookbooks/madison-server/recipes/default.rb
  ================================================================================
  
  Net::HTTPFatalError
  -------------------
  500 "Internal Server Error"
  
  Cookbook Trace:
  ---------------
    /root/chef-solo/local-mode-cache/cache/cookbooks/lamp-server/recipes/configure-sites.rb:50:in `rescue in block in from_file'
    /root/chef-solo/local-mode-cache/cache/cookbooks/lamp-server/recipes/configure-sites.rb:47:in `block in from_file'
    /root/chef-solo/local-mode-cache/cache/cookbooks/lamp-server/recipes/configure-sites.rb:45:in `each'
    /root/chef-solo/local-mode-cache/cache/cookbooks/lamp-server/recipes/configure-sites.rb:45:in `from_file'
    /root/chef-solo/local-mode-cache/cache/cookbooks/lamp-server/recipes/default.rb:15:in `from_file'
    /root/chef-solo/local-mode-cache/cache/cookbooks/madison-server/recipes/default.rb:8:in `from_file'
  
  Relevant File Content:
  ----------------------
  /root/chef-solo/local-mode-cache/cache/cookbooks/lamp-server/recipes/configure-sites.rb:
  
   43:  end
   44:  
   45:  sites.each do |site_name|
   46:    # Get the users' real data from the vault.
   47:    begin
   48:      Chef::EncryptedDataBagItem.load_secret
   49:    rescue
   50>>     full_site = Chef::DataBagItem.load('sites', site_name)
   51:    else
   52:      full_site = Chef::EncryptedDataBagItem.load('sites', site_name).to_hash
   53:    end
   54:  
   55:    # If the node is one this site belongs to, set it up on the box.
   56:    if full_site['servers'] and full_site['servers'].include? node.name
   57:  
   58:      # Apache setup.
   59:  
  
  Platform:
  ---------
  x86_64-linux-gnu
  
  
  Running handlers:
[2016-11-15T16:43:23+00:00] ERROR: Running exception handlers
  Running handlers complete
[2016-11-15T16:43:23+00:00] ERROR: Exception handlers complete
  Chef Client failed. 5 resources updated in 35 seconds
[2016-11-15T16:43:23+00:00] FATAL: Stacktrace dumped to /root/chef-solo/local-mode-cache/cache/chef-stacktrace.out
[2016-11-15T16:43:23+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-11-15T16:43:23+00:00] ERROR: 500 "Internal Server Error"
[2016-11-15T16:43:23+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.
Makefile:107: recipe for target 'chef-cook' failed
make: *** [chef-cook] Error 100
```

**Comment by sethetter** [comment]
@IuliiSe did you configure a site in `config/chef/data_bags/sites/`? There is an example in there.

**Comment by IuliiSe** [comment]
@sethetter yes, i did configure madison.json. Just double checked it. Changed url to IP instead of domain name. Still `chef-cook` returns errors.

```
    ================================================================================
    Error executing action `install` on resource 'apt_package[mariadb-server-10.0]'
    ================================================================================
    
    Mixlib::ShellOut::ShellCommandFailed
    ------------------------------------
    Expected process to exit with [0], but received '100'
    ---- Begin output of apt-get -q -y install mariadb-server-10.0=10.0.28+maria-1~xenial ----
    STDOUT: Reading package lists...
    Building dependency tree...
    Reading state information...
    Some packages could not be installed. This may mean that you have
    requested an impossible situation or if you are using the unstable
    distribution that some required packages have not yet been created
    or been moved out of Incoming.
    The following information may help to resolve the situation:
    
    The following packages have unmet dependencies:
     mariadb-server-10.0 : Depends: mariadb-client-10.0 (>= 10.0.28+maria-1~xenial) but it is not going to be installed
                           Depends: mariadb-server-core-10.0 (>= 10.0.28+maria-1~xenial) but it is not going to be installed
    STDERR: E: Unable to correct problems, you have held broken packages.
    ---- End output of apt-get -q -y install mariadb-server-10.0=10.0.28+maria-1~xenial ----
    Ran apt-get -q -y install mariadb-server-10.0=10.0.28+maria-1~xenial returned 100
    
    Cookbook Trace:
    ---------------
    /root/chef-solo/local-mode-cache/cache/cookbooks/compat_resource/files/lib/chef_compat/monkeypatches/chef/runner.rb:41:in `run_action'
    
    Resource Declaration:
    ---------------------
    # In /root/chef-solo/local-mode-cache/cache/cookbooks/mariadb/recipes/_debian_server.rb
    
     53: package "mariadb-server-#{node['mariadb']['install']['version']}" do
     54:   action :install
     55: end
    
    Compiled Resource:
    ------------------
    # Declared in /root/chef-solo/local-mode-cache/cache/cookbooks/mariadb/recipes/_debian_server.rb:53:in `from_file'
    
    apt_package("mariadb-server-10.0") do
      package_name "mariadb-server-10.0"
      action [:install]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      declared_type :package
      cookbook_name "mariadb"
      recipe_name "_debian_server"
    end
    
    Platform:
    ---------
    x86_64-linux-gnu
    
Recipe: chef-client::init_service
  * service[chef-client] action restart
    - restart service service[chef-client]

Running handlers:
[2016-11-15T21:53:22+00:00] ERROR: Running exception handlers
Running handlers complete
[2016-11-15T21:53:22+00:00] ERROR: Exception handlers complete
Chef Client failed. 45 resources updated in 54 seconds
[2016-11-15T21:53:22+00:00] FATAL: Stacktrace dumped to /root/chef-solo/local-mode-cache/cache/chef-stacktrace.out
[2016-11-15T21:53:22+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-11-15T21:53:22+00:00] ERROR: apt_package[mariadb-server-10.0] (mariadb::_debian_server line 53) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '100'
---- Begin output of apt-get -q -y install mariadb-server-10.0=10.0.28+maria-1~xenial ----
STDOUT: Reading package lists...
Building dependency tree...
Reading state information...
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 mariadb-server-10.0 : Depends: mariadb-client-10.0 (>= 10.0.28+maria-1~xenial) but it is not going to be installed
                       Depends: mariadb-server-core-10.0 (>= 10.0.28+maria-1~xenial) but it is not going to be installed
STDERR: E: Unable to correct problems, you have held broken packages.
---- End output of apt-get -q -y install mariadb-server-10.0=10.0.28+maria-1~xenial ----
Ran apt-get -q -y install mariadb-server-10.0=10.0.28+maria-1~xenial returned 100
[2016-11-15T21:53:22+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.
Makefile:107: recipe for target 'chef-cook' failed
make: *** [chef-cook] Error 100
```

**Comment by IuliiSe** [comment]
@sethetter Does `chef-cook `need to install mariadb (as above)?

**Comment by sethetter** [comment]
@IuliiSe I think the issue may be the Ubuntu version. Could you try the provisioning on an Ubuntu 14.04 LTS server?

**Comment by IuliiSe** [comment]
@sethetter there is a new issue with berkshelf

```
WARNING: #<LoadError: cannot load such file -- berkshelf>
WARNING: Berkshelf could not be loaded
WARNING: Please add the berkshelf gem to your Gemfile or install it manually with `gem install berkshelf`
Uploading the kitchen...
```

**Comment by sethetter** [comment]
@IuliiSe try `gem install berkshelf` for now. I added it to the `Gemfile` in the `dev` branch. Thanks for finding that!

**Comment by IuliiSe** [comment]
@sethetter thank you. it worked.
now I get this after `chef-cook` :(
```
Compiled Resource:
    ------------------
    # Declared in /root/chef-solo/local-mode-cache/cache/cookbooks/lamp-server/recipes/configure-sites.rb:154:in `block in from_file'
    
    mysql_database("madison") do
      provider Chef::Provider::Database::Mysql
      action [:create]
      retries 0
      retry_delay 2
      default_guard_interpreter :default
      database_name "madison"
      declared_type :mysql_database
      cookbook_name "lamp-server"
      recipe_name "configure-sites"
      connection {:host=>"127.0.0.1", :username=>"root", :password=>""}
    end
    
    Platform:
    ---------
    x86_64-linux
    
Recipe: apache2::default
  * service[apache2] action reload (skipped due to only_if)
  * service[apache2] action restart (skipped due to only_if)

Running handlers:
[2016-11-18T21:20:28+00:00] ERROR: Running exception handlers
Running handlers complete
[2016-11-18T21:20:28+00:00] ERROR: Exception handlers complete
Chef Client failed. 11 resources updated in 57 seconds
[2016-11-18T21:20:28+00:00] FATAL: Stacktrace dumped to /root/chef-solo/local-mode-cache/cache/chef-stacktrace.out
[2016-11-18T21:20:28+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2016-11-18T21:20:28+00:00] ERROR: mysql_database[madison] (lamp-server::configure-sites line 154) had an error: Mysql2::Error: Access denied for user 'root'@'localhost' (using password: YES)
[2016-11-18T21:20:28+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: RuntimeError: chef-solo failed. See output above.
make: *** [chef-cook] Error 100
```
I can login into mysql as root with the pass if `mysql -u root -p`

```
Enter password: 
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 40
Server version: 10.0.28-MariaDB-1~trusty mariadb.org binary distribution

Copyright (c) 2000, 2016, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]> SHOW GRANTS FOR 'root'@'localhost'\G;
*************************** 1. row ***************************
Grants for root@localhost: GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost' IDENTIFIED BY PASSWORD '*' WITH GRANT OPTION
*************************** 2. row ***************************
Grants for root@localhost: GRANT ALL PRIVILEGES ON `dbsunrise`.* TO 'root'@'localhost'
*************************** 3. row ***************************
Grants for root@localhost: GRANT ALL PRIVILEGES ON `sunrise`.* TO 'root'@'localhost'
*************************** 4. row ***************************
Grants for root@localhost: GRANT ALL PRIVILEGES ON `madison`.* TO 'root'@'localhost'
*************************** 5. row ***************************
Grants for root@localhost: GRANT ALL PRIVILEGES ON `%`.* TO 'root'@'localhost' WITH GRANT OPTION
*************************** 6. row ***************************
Grants for root@localhost: GRANT PROXY ON ''@'%' TO 'root'@'localhost' WITH GRANT OPTION
6 rows in set (0.00 sec)
```

**Comment by IuliiSe** [comment]
This is solved. Thank you @sethetter !

**Comment by sethetter** [comment]
Great! What was the solution?

**Comment by IuliiSe** [comment]
The key issue was with the Ubuntu version. Needed to downgrade to Ubuntu 14.04 LTS.
Needed to fetch the latest Gemfile from dev and update ssh keys.
But, `cap deploy` causes a new issue. I opened a new ticket asking for support.
